version: "3.9"

services:
  server:
    build: .
    command: supervisord -c supervisord.conf -n
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - 9001:9001
    hostname: server
    env_file:
      - envs/docker.env

  nginx:
    restart: always
    image: nginx:1.21
    working_dir: /code
    volumes:
      - .:/code
    command: [ nginx-debug, '-c', '/code/nginx.conf' ]
    ports:
      - 8080:8080
      - 443:443
